/*
 * static_model.h
 *
 * automatically generated from ../model/model_cswi.icd
 */

#ifndef STATIC_MODEL_H_
#define STATIC_MODEL_H_

#include <stdlib.h>
#include "iec61850_model.h"

extern IedModel iedModel;
extern LogicalDevice iedModel_CSWI_Control;
extern LogicalNode   iedModel_CSWI_Control_LLN0;
extern DataObject    iedModel_CSWI_Control_LLN0_Mod;
extern DataAttribute iedModel_CSWI_Control_LLN0_Mod_stVal;
extern DataAttribute iedModel_CSWI_Control_LLN0_Mod_q;
extern DataAttribute iedModel_CSWI_Control_LLN0_Mod_t;
extern DataAttribute iedModel_CSWI_Control_LLN0_Mod_ctlModel;
extern DataObject    iedModel_CSWI_Control_LLN0_Beh;
extern DataAttribute iedModel_CSWI_Control_LLN0_Beh_stVal;
extern DataAttribute iedModel_CSWI_Control_LLN0_Beh_q;
extern DataAttribute iedModel_CSWI_Control_LLN0_Beh_t;
extern DataObject    iedModel_CSWI_Control_LLN0_Health;
extern DataAttribute iedModel_CSWI_Control_LLN0_Health_stVal;
extern DataAttribute iedModel_CSWI_Control_LLN0_Health_q;
extern DataAttribute iedModel_CSWI_Control_LLN0_Health_t;
extern DataObject    iedModel_CSWI_Control_LLN0_NamPlt;
extern DataAttribute iedModel_CSWI_Control_LLN0_NamPlt_vendor;
extern DataAttribute iedModel_CSWI_Control_LLN0_NamPlt_swRev;
extern LogicalNode   iedModel_CSWI_Control_CSWI1;
extern DataObject    iedModel_CSWI_Control_CSWI1_Mod;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Mod_stVal;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Mod_q;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Mod_t;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Mod_ctlModel;
extern DataObject    iedModel_CSWI_Control_CSWI1_Beh;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Beh_stVal;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Beh_q;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Beh_t;
extern DataObject    iedModel_CSWI_Control_CSWI1_Health;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Health_stVal;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Health_q;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Health_t;
extern DataObject    iedModel_CSWI_Control_CSWI1_NamPlt;
extern DataAttribute iedModel_CSWI_Control_CSWI1_NamPlt_vendor;
extern DataAttribute iedModel_CSWI_Control_CSWI1_NamPlt_swRev;
extern DataObject    iedModel_CSWI_Control_CSWI1_Loc;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Loc_stVal;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Loc_q;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Loc_t;
extern DataObject    iedModel_CSWI_Control_CSWI1_OpCnt;
extern DataAttribute iedModel_CSWI_Control_CSWI1_OpCnt_stVal;
extern DataAttribute iedModel_CSWI_Control_CSWI1_OpCnt_q;
extern DataAttribute iedModel_CSWI_Control_CSWI1_OpCnt_t;
extern DataObject    iedModel_CSWI_Control_CSWI1_Pos;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Pos_stVal;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Pos_q;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Pos_t;
extern DataAttribute iedModel_CSWI_Control_CSWI1_Pos_ctlModel;



#define IEDMODEL_CSWI_Control (&iedModel_CSWI_Control)
#define IEDMODEL_CSWI_Control_LLN0 (&iedModel_CSWI_Control_LLN0)
#define IEDMODEL_CSWI_Control_LLN0_Mod (&iedModel_CSWI_Control_LLN0_Mod)
#define IEDMODEL_CSWI_Control_LLN0_Mod_stVal (&iedModel_CSWI_Control_LLN0_Mod_stVal)
#define IEDMODEL_CSWI_Control_LLN0_Mod_q (&iedModel_CSWI_Control_LLN0_Mod_q)
#define IEDMODEL_CSWI_Control_LLN0_Mod_t (&iedModel_CSWI_Control_LLN0_Mod_t)
#define IEDMODEL_CSWI_Control_LLN0_Mod_ctlModel (&iedModel_CSWI_Control_LLN0_Mod_ctlModel)
#define IEDMODEL_CSWI_Control_LLN0_Beh (&iedModel_CSWI_Control_LLN0_Beh)
#define IEDMODEL_CSWI_Control_LLN0_Beh_stVal (&iedModel_CSWI_Control_LLN0_Beh_stVal)
#define IEDMODEL_CSWI_Control_LLN0_Beh_q (&iedModel_CSWI_Control_LLN0_Beh_q)
#define IEDMODEL_CSWI_Control_LLN0_Beh_t (&iedModel_CSWI_Control_LLN0_Beh_t)
#define IEDMODEL_CSWI_Control_LLN0_Health (&iedModel_CSWI_Control_LLN0_Health)
#define IEDMODEL_CSWI_Control_LLN0_Health_stVal (&iedModel_CSWI_Control_LLN0_Health_stVal)
#define IEDMODEL_CSWI_Control_LLN0_Health_q (&iedModel_CSWI_Control_LLN0_Health_q)
#define IEDMODEL_CSWI_Control_LLN0_Health_t (&iedModel_CSWI_Control_LLN0_Health_t)
#define IEDMODEL_CSWI_Control_LLN0_NamPlt (&iedModel_CSWI_Control_LLN0_NamPlt)
#define IEDMODEL_CSWI_Control_LLN0_NamPlt_vendor (&iedModel_CSWI_Control_LLN0_NamPlt_vendor)
#define IEDMODEL_CSWI_Control_LLN0_NamPlt_swRev (&iedModel_CSWI_Control_LLN0_NamPlt_swRev)
#define IEDMODEL_CSWI_Control_CSWI1 (&iedModel_CSWI_Control_CSWI1)
#define IEDMODEL_CSWI_Control_CSWI1_Mod (&iedModel_CSWI_Control_CSWI1_Mod)
#define IEDMODEL_CSWI_Control_CSWI1_Mod_stVal (&iedModel_CSWI_Control_CSWI1_Mod_stVal)
#define IEDMODEL_CSWI_Control_CSWI1_Mod_q (&iedModel_CSWI_Control_CSWI1_Mod_q)
#define IEDMODEL_CSWI_Control_CSWI1_Mod_t (&iedModel_CSWI_Control_CSWI1_Mod_t)
#define IEDMODEL_CSWI_Control_CSWI1_Mod_ctlModel (&iedModel_CSWI_Control_CSWI1_Mod_ctlModel)
#define IEDMODEL_CSWI_Control_CSWI1_Beh (&iedModel_CSWI_Control_CSWI1_Beh)
#define IEDMODEL_CSWI_Control_CSWI1_Beh_stVal (&iedModel_CSWI_Control_CSWI1_Beh_stVal)
#define IEDMODEL_CSWI_Control_CSWI1_Beh_q (&iedModel_CSWI_Control_CSWI1_Beh_q)
#define IEDMODEL_CSWI_Control_CSWI1_Beh_t (&iedModel_CSWI_Control_CSWI1_Beh_t)
#define IEDMODEL_CSWI_Control_CSWI1_Health (&iedModel_CSWI_Control_CSWI1_Health)
#define IEDMODEL_CSWI_Control_CSWI1_Health_stVal (&iedModel_CSWI_Control_CSWI1_Health_stVal)
#define IEDMODEL_CSWI_Control_CSWI1_Health_q (&iedModel_CSWI_Control_CSWI1_Health_q)
#define IEDMODEL_CSWI_Control_CSWI1_Health_t (&iedModel_CSWI_Control_CSWI1_Health_t)
#define IEDMODEL_CSWI_Control_CSWI1_NamPlt (&iedModel_CSWI_Control_CSWI1_NamPlt)
#define IEDMODEL_CSWI_Control_CSWI1_NamPlt_vendor (&iedModel_CSWI_Control_CSWI1_NamPlt_vendor)
#define IEDMODEL_CSWI_Control_CSWI1_NamPlt_swRev (&iedModel_CSWI_Control_CSWI1_NamPlt_swRev)
#define IEDMODEL_CSWI_Control_CSWI1_Loc (&iedModel_CSWI_Control_CSWI1_Loc)
#define IEDMODEL_CSWI_Control_CSWI1_Loc_stVal (&iedModel_CSWI_Control_CSWI1_Loc_stVal)
#define IEDMODEL_CSWI_Control_CSWI1_Loc_q (&iedModel_CSWI_Control_CSWI1_Loc_q)
#define IEDMODEL_CSWI_Control_CSWI1_Loc_t (&iedModel_CSWI_Control_CSWI1_Loc_t)
#define IEDMODEL_CSWI_Control_CSWI1_OpCnt (&iedModel_CSWI_Control_CSWI1_OpCnt)
#define IEDMODEL_CSWI_Control_CSWI1_OpCnt_stVal (&iedModel_CSWI_Control_CSWI1_OpCnt_stVal)
#define IEDMODEL_CSWI_Control_CSWI1_OpCnt_q (&iedModel_CSWI_Control_CSWI1_OpCnt_q)
#define IEDMODEL_CSWI_Control_CSWI1_OpCnt_t (&iedModel_CSWI_Control_CSWI1_OpCnt_t)
#define IEDMODEL_CSWI_Control_CSWI1_Pos (&iedModel_CSWI_Control_CSWI1_Pos)
#define IEDMODEL_CSWI_Control_CSWI1_Pos_stVal (&iedModel_CSWI_Control_CSWI1_Pos_stVal)
#define IEDMODEL_CSWI_Control_CSWI1_Pos_q (&iedModel_CSWI_Control_CSWI1_Pos_q)
#define IEDMODEL_CSWI_Control_CSWI1_Pos_t (&iedModel_CSWI_Control_CSWI1_Pos_t)
#define IEDMODEL_CSWI_Control_CSWI1_Pos_ctlModel (&iedModel_CSWI_Control_CSWI1_Pos_ctlModel)

#endif /* STATIC_MODEL_H_ */

