version: '3.8'

services:
  xcbr_simulator:
    build:
      context: .
      dockerfile: src/xcbr/Dockerfile
    container_name: xcbr_simulator
    volumes:
      - /usr/local:/usr/local   # Bind mount untuk library
    ports:
      - "5003:5003"

  # cswi_simulator:
  #   build:
  #     context: .
  #     dockerfile: src/cswi/Dockerfile
  #   container_name: cswi_simulator
  #   volumes:
  #     - /usr/local:/usr/local   # Bind mount untuk library
  #   ports:
  #     - "5001:5001"

  # mmxu_simulator:
  #   build:
  #     context: .
  #     dockerfile: src/mmxu/Dockerfile
  #   container_name: mmxu_simulator
  #   volumes:
  #     - /usr/local:/usr/local   # Bind mount untuk library
  #   ports:
  #     - "5002:5002"
