# docker-compose.yml
version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: libiec61850-base:latest

  model-generator:
    build:
      context: .
      dockerfile: Dockerfile.model-generator
    volumes:
      - ./model:/app/model
      - ./src:/app/src
    depends_on:
      - base

  cswi:
    build:
      context: .
      dockerfile: src/cswi/Dockerfile
    container_name: cswi-simulator
    depends_on:
      - model-generator
    ports:
      - "10102:10102"
    volumes:
      - ./model:/app/model
      - ./src/cswi:/app/src/cswi
    networks:
      - iec61850-network

  mmxu:
    build:
      context: .
      dockerfile: src/mmxu/Dockerfile
    container_name: mmxu-simulator
    depends_on:
      - model-generator
    ports:
      - "10103:10103"
    volumes:
      - ./model:/app/model
      - ./src/mmxu:/app/src/mmxu
    networks:
      - iec61850-network

  xcbr:
    build:
      context: .
      dockerfile: src/xcbr/Dockerfile
    container_name: xcbr-simulator
    depends_on:
      - model-generator
    ports:
      - "10104:10104"
    volumes:
      - ./model:/app/model
      - ./src/xcbr:/app/src/xcbr
    networks:
      - iec61850-network

networks:
  iec61850-network:
    name: iec61850-network

